# MockS3 Metadata Service 配置文件

# 服务基本配置
server:
  host: "0.0.0.0"
  port: 8081
  environment: "development"
  version: "1.0.0"

# 数据库配置
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database: "mocks3_metadata"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"

# 可观测性配置
observability:
  service_name: "metadata-service"
  service_version: "1.0.0"
  environment: "development"
  otlp_endpoint: "localhost:4318"
  log_level: "info"
  sampling_ratio: 1.0
  export_interval: "30s"

# Consul 配置
consul:
  address: "localhost:8500"
  enabled: true
  register: true
  health_check_interval: "10s"
  deregister_critical_after: "1m"

# 健康检查配置
health:
  check_interval: "30s"
  timeout: "5s"
  endpoint: "/health"

# 性能配置
performance:
  max_connections: 1000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  request_size_limit: "10MB"

# 缓存配置
cache:
  enabled: true
  ttl: 300
  max_size: 100
  cleanup_interval: "5m"

# 业务配置
business:
  max_objects_per_bucket: 1000000
  max_metadata_size: "1KB"
  allow_object_overwrite: true
  enable_versioning: false