# MockS3 Mock Error Service 配置文件

# 服务基本配置
server:
  host: "0.0.0.0"
  port: 8085
  environment: "development"
  version: "1.0.0"

# Consul 配置
consul:
  address: "localhost:8500"
  enabled: true
  register: true
  health_check_interval: "10s"
  deregister_critical_after: "1m"

# 错误引擎配置
error_engine:
  max_rules: 1000
  enable_scheduling: true
  default_probability: 0.1
  enable_statistics: true
  stat_retention_hours: 24
  rule_refresh_interval: "30s"
  max_concurrent_injections: 100

# 错误注入配置
injection:
  max_delay_ms: 10000
  enable_http_errors: true
  enable_network_errors: true
  enable_database_errors: true
  enable_storage_errors: true
  global_probability: 1.0
  
  # HTTP 错误配置
  http_errors:
    - status_code: 500
      probability: 0.05
      delay_ms: 0
    - status_code: 503
      probability: 0.03
      delay_ms: 1000
    - status_code: 404
      probability: 0.02
      delay_ms: 0
    - status_code: 429
      probability: 0.01
      delay_ms: 5000

  # 网络错误配置
  network_errors:
    - type: "connection_timeout"
      probability: 0.02
      delay_ms: 5000
    - type: "connection_refused"
      probability: 0.01
      delay_ms: 0
    - type: "dns_failure"
      probability: 0.005
      delay_ms: 3000

  # 数据库错误配置
  database_errors:
    - type: "connection_pool_exhausted"
      probability: 0.01
      delay_ms: 2000
    - type: "deadlock"
      probability: 0.005
      delay_ms: 1000
    - type: "constraint_violation"
      probability: 0.003
      delay_ms: 0

  # 存储错误配置
  storage_errors:
    - type: "disk_full"
      probability: 0.002
      delay_ms: 0
    - type: "io_error"
      probability: 0.005
      delay_ms: 1000
    - type: "permission_denied"
      probability: 0.001
      delay_ms: 0

# 规则模板配置
rule_templates:
  - name: "high_latency"
    description: "高延迟注入"
    type: "delay"
    min_delay_ms: 1000
    max_delay_ms: 5000
    probability: 0.1
  
  - name: "service_unavailable"
    description: "服务不可用"
    type: "http_error"
    status_code: 503
    probability: 0.05
  
  - name: "timeout"
    description: "请求超时"
    type: "timeout"
    timeout_ms: 30000
    probability: 0.03

# 场景配置
scenarios:
  - name: "chaos_monkey"
    description: "混沌工程测试场景"
    enabled: false
    duration: "1h"
    rules:
      - template: "high_latency"
        target_services: ["storage", "metadata"]
        probability: 0.2
      - template: "service_unavailable"
        target_services: ["third-party"]
        probability: 0.1

  - name: "load_test"
    description: "负载测试场景"
    enabled: false
    duration: "30m"
    rules:
      - template: "timeout"
        target_services: ["*"]
        probability: 0.05

# 可观测性配置
observability:
  service_name: "mock-error-service"
  service_version: "1.0.0"
  environment: "development"
  otlp_endpoint: "localhost:4318"
  log_level: "info"
  sampling_ratio: 1.0
  export_interval: "30s"

# 健康检查配置
health:
  check_interval: "30s"
  timeout: "5s"
  endpoint: "/health"

# 性能配置
performance:
  max_connections: 500
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "60s"
  request_size_limit: "1MB"

# 监控和统计配置
monitoring:
  enable_metrics: true
  metrics_interval: "10s"
  track_injection_count: true
  track_success_rate: true
  track_latency: true
  export_dashboard: true